#spring.application.name=Spring_Security

spring:
  application:
    name: Spring_Security

  config:
    import: optional:file:.env[.properties]


  data:
    redis:
      host: localhost
      port: 6379

#create user '사용자'@'%' identified by '비밀번호';
#grant all privileges on DBNAME.* to userID@'%';
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  mail:
    protocol: smtp
    port: 587
    username: ${GOOGLE_ID}
    password: ${APP_PASSWORD}
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret : ${JWT_SECRET}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${IAM_ACCESS_KEY}
      secret-key: ${IAM_SECRET_KEY}
    stack:
      auto: false
    region:
      static: ${AWS_REGION}